### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by jazelly** [jazelly/FinetuneLLMs#4]
We need a Pull Request template for this repo, so it's easier for reviewers to review PR with context.

There are many PR template examples that you can check on other repoes, e.g.

- [PR template in anything-llm](https://github.com/Mintplex-Labs/anything-llm/blob/master/pull_request_template.md?plain=1)

This doesn't need to be perfect as we can always iterate.

We also need a contribution guide for external contributors to contribute.

 - [ ] PR template
 - [ ] Contribution guide

**Comment by Jaishree2310** [comment]
@jazelly could you please elaborate more on this issue?

**Comment by jazelly** [comment]
Hi @Jaishree2310 I have updated the issue with description. Feel free to raise a PR

**Comment by xwan99** [comment]
is it possible to also add a contributing guide. I think that's more helpful

**Comment by jazelly** [comment]
Sounds good @xwan99  updated the issue

**Comment by jazelly** [comment]
fixed by https://github.com/jazelly/FinetuneLLMs/pull/14
