### ISSUE TITLE
Follow the design and change the header UI to permalink

### ISSUE THREAD

**Issue by jazelly** [jazelly/FinetuneLLMs#8]
Check this design, and notice the header `Dashboard > TV Series > Add a New TV Series`

We are currently not using this style, but we should, as the current floating header is ugly.

![Image](https://github.com/jazelly/FinetuneLLMs/assets/28685065/2f4d5248-a6ce-4de7-989d-0d0f62d9a652)

**Comment by Thrassa** [comment]
I'll take this
